/**
 * BCI 领域英文标题中译工具
 * 基于术语词典的规则翻译，覆盖神经科学与脑机接口核心词汇
 */

// ── 术语词典（按匹配优先级排列：长词组优先） ──────────────

const DICT = [
    // ── 复合短语（优先匹配）─────────────────────────
    ['brain-computer interface', '脑机接口'],
    ['brain computer interface', '脑机接口'],
    ['brain-machine interface', '脑机接口'],
    ['brain-spine interface', '脑脊接口'],
    ['deep brain stimulation', '深部脑刺激'],
    ['spinal cord injury', '脊髓损伤'],
    ['motor cortex', '运动皮层'],
    ['prefrontal cortex', '前额叶皮层'],
    ['somatosensory cortex', '体感皮层'],
    ['visual cortex', '视觉皮层'],
    ['cerebral cortex', '大脑皮层'],
    ['neural interface', '神经接口'],
    ['neural network', '神经网络'],
    ['neural signal', '神经信号'],
    ['neural recording', '神经记录'],
    ['neural decoding', '神经解码'],
    ['neural data', '神经数据'],
    ['neural activity', '神经活动'],
    ['neural implant', '神经植入物'],
    ['neural probe', '神经探针'],
    ['neural engineering', '神经工程'],
    ['neural prosthesis', '神经假体'],
    ['neural prosthetics', '神经假体'],
    ['neural modulation', '神经调控'],
    ['closed-loop', '闭环'],
    ['closed loop', '闭环'],
    ['open-loop', '开环'],
    ['real-time', '实时'],
    ['real time', '实时'],
    ['non-invasive', '无创'],
    ['non invasive', '无创'],
    ['minimally invasive', '微创'],
    ['first-in-human', '首次人体'],
    ['proof-of-concept', '概念验证'],
    ['proof of concept', '概念验证'],
    ['state-of-the-art', '最先进'],
    ['machine learning', '机器学习'],
    ['deep learning', '深度学习'],
    ['reinforcement learning', '强化学习'],
    ['transfer learning', '迁移学习'],
    ['federated learning', '联邦学习'],
    ['self-supervised', '自监督'],
    ['semi-supervised', '半监督'],
    ['large language model', '大语言模型'],
    ['artificial intelligence', '人工智能'],
    ['clinical trial', '临床试验'],
    ['clinical trials', '临床试验'],
    ['randomized controlled trial', '随机对照试验'],
    ['longitudinal study', '纵向研究'],
    ['systematic review', '系统综述'],
    ['meta-analysis', '荟萃分析'],
    ['meta analysis', '荟萃分析'],
    ['motor neuron disease', '运动神经元病'],
    ['amyotrophic lateral sclerosis', '肌萎缩侧索硬化症'],
    ['treatment-resistant depression', '难治性抑郁症'],
    ['treatment resistant depression', '难治性抑郁症'],
    ['Parkinson\'s disease', '帕金森病'],
    ['Alzheimer\'s disease', '阿尔茨海默病'],
    ['signal processing', '信号处理'],
    ['signal quality', '信号质量'],
    ['data augmentation', '数据增强'],
    ['speech decoding', '语音解码'],
    ['motor intention', '运动意图'],
    ['motor imagery', '运动想象'],
    ['motor control', '运动控制'],
    ['robotic arm', '机械臂'],
    ['robotic limb', '机械肢体'],
    ['upper-limb', '上肢'],
    ['upper limb', '上肢'],
    ['lower-limb', '下肢'],
    ['lower limb', '下肢'],
    ['grip force', '抓握力'],
    ['tactile sensation', '触觉'],
    ['tactile feedback', '触觉反馈'],
    ['somatosensory feedback', '体感反馈'],
    ['sensory feedback', '感觉反馈'],
    ['electrode array', '电极阵列'],
    ['microelectrode array', '微电极阵列'],
    ['flexible electrode', '柔性电极'],
    ['thin-film', '薄膜'],
    ['thin film', '薄膜'],
    ['tissue reaction', '组织反应'],
    ['inflammatory response', '炎症反应'],
    ['glial scarring', '胶质瘢痕'],
    ['gene therapy', '基因治疗'],
    ['stem cell', '干细胞'],
    ['stem cells', '干细胞'],
    ['working memory', '工作记忆'],
    ['cognitive impairment', '认知障碍'],
    ['sleep restriction', '睡眠限制'],
    ['circadian clock', '生物钟'],
    ['brain tissue', '脑组织'],
    ['brain imaging', '脑成像'],
    ['functional connectivity', '功能连接'],
    ['structural connectome', '结构连接组'],
    ['diffusion tensor imaging', '弥散张量成像'],
    ['magnetic resonance', '磁共振'],
    ['blood-brain barrier', '血脑屏障'],
    ['high-density', '高密度'],
    ['high density', '高密度'],
    ['high-bandwidth', '高带宽'],
    ['high bandwidth', '高带宽'],
    ['wireless data', '无线数据'],
    ['wireless transmission', '无线传输'],
    ['market projected', '市场预测'],
    ['series c', 'C轮融资'],
    ['series b', 'B轮融资'],
    ['series a', 'A轮融资'],
    ['FDA clearance', 'FDA批准'],
    ['FDA approval', 'FDA批准'],
    ['FDA approved', 'FDA已批准'],

    // ── 单词 ──────────────────────────────────────────
    ['neuroscience', '神经科学'],
    ['neurosurgery', '神经外科'],
    ['neuromodulation', '神经调控'],
    ['neuroprosthetic', '神经假体'],
    ['neuroprosthetics', '神经假体'],
    ['neuroimaging', '神经影像'],
    ['neuroplasticity', '神经可塑性'],
    ['neurotechnology', '神经技术'],
    ['neurostimulation', '神经刺激'],
    ['neuroengineering', '神经工程'],
    ['electrophysiology', '电生理学'],
    ['electroencephalography', '脑电图'],
    ['electrocorticography', '皮层脑电图'],
    ['intracortical', '皮层内'],
    ['intracranial', '颅内'],
    ['endovascular', '血管内'],
    ['optogenetic', '光遗传学'],
    ['optogenetics', '光遗传学'],
    ['biocompatible', '生物相容'],
    ['biocompatibility', '生物相容性'],
    ['biodegradable', '可降解'],
    ['implantable', '可植入'],
    ['implanted', '植入的'],
    ['implant', '植入物'],
    ['implantation', '植入'],
    ['prosthetic', '假体'],
    ['prosthetics', '假体'],
    ['prosthesis', '假体'],
    ['paralyzed', '瘫痪的'],
    ['paralysis', '瘫痪'],
    ['tetraplegia', '四肢瘫痪'],
    ['quadriplegia', '四肢瘫痪'],
    ['paraplegia', '截瘫'],
    ['amputee', '截肢者'],
    ['amputees', '截肢者'],
    ['wheelchair', '轮椅'],
    ['rehabilitation', '康复'],
    ['therapeutic', '治疗的'],
    ['therapy', '治疗'],
    ['chronic', '慢性'],
    ['acute', '急性'],
    ['invasive', '有创'],
    ['cortical', '皮层'],
    ['subcortical', '皮层下'],
    ['hippocampal', '海马体'],
    ['hippocampus', '海马体'],
    ['thalamus', '丘脑'],
    ['cerebellum', '小脑'],
    ['neurons', '神经元'],
    ['neuron', '神经元'],
    ['synaptic', '突触'],
    ['synapse', '突触'],
    ['axon', '轴突'],
    ['dendrite', '树突'],
    ['spike', '脉冲'],
    ['spiking', '脉冲'],
    ['decoder', '解码器'],
    ['decoding', '解码'],
    ['encoder', '编码器'],
    ['encoding', '编码'],
    ['classifier', '分类器'],
    ['classification', '分类'],
    ['segmentation', '分割'],
    ['regression', '回归'],
    ['calibration', '校准'],
    ['pretraining', '预训练'],
    ['fine-tuning', '微调'],
    ['transformer', 'Transformer模型'],
    ['benchmark', '基准测试'],
    ['accuracy', '准确率'],
    ['latency', '延迟'],
    ['bandwidth', '带宽'],
    ['impedance', '阻抗'],
    ['channel', '通道'],
    ['channels', '通道'],
    ['electrode', '电极'],
    ['electrodes', '电极'],
    ['sensor', '传感器'],
    ['sensors', '传感器'],
    ['wireless', '无线'],
    ['wearable', '可穿戴'],
    ['portable', '便携'],
    ['ultrasound', '超声波'],
    ['graphene', '石墨烯'],
    ['silicon', '硅基'],
    ['polymer', '聚合物'],
    ['EEG', '脑电图'],
    ['ECoG', '皮层电图'],
    ['fMRI', '功能磁共振'],
    ['MEG', '脑磁图'],
    ['BCI', '脑机接口'],
    ['BCIs', '脑机接口'],
    ['ALS', '渐冻症'],
    ['DBS', '深部脑刺激'],
    ['LFP', '局部场电位'],
    ['SNN', '脉冲神经网络'],
    ['CNS', '中枢神经系统'],
    ['PNS', '外周神经系统'],
    ['DARPA', '美国国防高级研究计划局'],
    ['NIH', '美国国立卫生研究院'],
    ['feasibility', '可行性'],
    ['efficacy', '疗效'],
    ['safety', '安全性'],
    ['adverse', '不良'],
    ['biomarker', '生物标志物'],
    ['biomarkers', '生物标志物'],
    ['phenotype', '表型'],
    ['phenotypes', '表型'],
    ['genotype', '基因型'],
    ['proteomics', '蛋白质组学'],
    ['genomics', '基因组学'],
    ['epigenetic', '表观遗传'],
    ['diffusion', '扩散'],
    ['stimulation', '刺激'],
    ['modulation', '调控'],
    ['restoration', '恢复'],
    ['restores', '恢复'],
    ['restore', '恢复'],
    ['voluntary', '自主的'],
    ['walking', '行走'],
    ['grasping', '抓取'],
    ['reaching', '伸展'],
    ['speaking', '说话'],
    ['communication', '交流'],
    ['cognitive', '认知'],
    ['behavioral', '行为'],
    ['psychiatric', '精神'],
    ['neurological', '神经系统'],
    ['degenerative', '退行性'],
    ['traumatic', '创伤性'],
    ['ischemic', '缺血性'],
    ['hemorrhagic', '出血性'],
    ['stroke', '中风'],
    ['epilepsy', '癫痫'],
    ['seizure', '癫痫发作'],
    ['depression', '抑郁症'],
    ['anxiety', '焦虑症'],
    ['PTSD', '创伤后应激障碍'],
    ['autism', '自闭症'],
    ['schizophrenia', '精神分裂症'],
    ['dementia', '痴呆'],
    ['neuropathy', '神经病变'],
    ['primate', '灵长类'],
    ['primates', '灵长类'],
    ['macaque', '猕猴'],
    ['rodent', '啮齿类'],
    ['mouse', '小鼠'],
    ['mice', '小鼠'],
    ['rat', '大鼠'],
    ['rats', '大鼠'],
    ['in vivo', '体内'],
    ['in vitro', '体外'],
    ['ex vivo', '离体'],
    ['patient', '患者'],
    ['patients', '患者'],
    ['participant', '受试者'],
    ['participants', '受试者'],
    ['subject', '受试者'],
    ['subjects', '受试者'],
    ['novel', '新型'],
    ['robust', '稳健的'],
    ['scalable', '可扩展的'],
    ['comprehensive', '综合的'],
    ['significant', '显著的'],
    ['sustainable', '可持续的'],
    ['unprecedented', '前所未有的'],
    ['promising', '有前景的'],
    ['emerges', '出现'],
    ['emerging', '新兴'],
    ['advances', '进展'],
    ['breakthrough', '突破'],
    ['innovation', '创新'],
    ['paradigm', '范式'],
    ['framework', '框架'],
    ['architecture', '架构'],
    ['algorithm', '算法'],
    ['protocol', '方案'],
    ['methodology', '方法学'],
    ['hypothesis', '假说'],
    ['demonstrates', '展示'],
    ['demonstrate', '展示'],
    ['reveals', '揭示'],
    ['reveal', '揭示'],
    ['achieves', '达到'],
    ['achieve', '达到'],
    ['enables', '实现'],
    ['enable', '实现'],
    ['enhances', '增强'],
    ['enhance', '增强'],
    ['improves', '改善'],
    ['improve', '改善'],
    ['reduces', '减少'],
    ['reduce', '减少'],
    ['identifies', '识别'],
    ['identify', '识别'],
    ['predicts', '预测'],
    ['predict', '预测'],
    ['validates', '验证'],
    ['validate', '验证'],
    ['evaluates', '评估'],
    ['evaluate', '评估'],
    ['investigates', '研究'],
    ['investigate', '研究'],
    ['characterizes', '表征'],
    ['characterize', '表征'],
    ['modulates', '调控'],
    ['modulate', '调控'],
    ['facilitates', '促进'],
    ['facilitate', '促进'],
    ['accelerates', '加速'],
    ['accelerate', '加速'],
    ['outperforms', '优于'],
    ['surpasses', '超越'],
    ['overcomes', '克服'],
    ['mitigates', '缓解'],
];

/**
 * 将英文标题翻译为中文（基于术语词典的近似翻译）
 * @param {string} title - 英文标题
 * @returns {string} 中文翻译
 */
function translateTitle(title) {
    if (!title) return '';

    // 若标题已含中文，不翻译
    if (/[\u4e00-\u9fff]/.test(title)) return '';

    let result = title;

    // 按词组长度降序排列 — 长词组优先匹配
    const sorted = [...DICT].sort((a, b) => b[0].length - a[0].length);

    for (const [en, zh] of sorted) {
        const regex = new RegExp(en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
        result = result.replace(regex, zh);
    }

    return result;
}

module.exports = { translateTitle };
